services:
  corrade:
    image: fixedbit/corrade:latest
    container_name: corrade
    tty: true
    restart: unless-stopped
    ports:
      - "54377:54377"
    volumes:
      - "${PWD}/data/config:/config"
      - "${PWD}/data/Cache:/corrade/Cache"
      - "${PWD}/data/Logs:/corrade/Logs"
      - "${PWD}/data/State:/corrade/State"
      - "${PWD}/data/Databases:/corrade/Databases"