name: Cron Corrade Version Check
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # We run on a cron every 12 hours from GitHub Actions

jobs:
  build:
    name: Check and build if needed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run cron_build.sh
        run: |
          chmod +x cron_build.sh
          ./cron_build.sh
